sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.coursier
jdk:
  - oraclejdk8
  - openjdk11
language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC3
script:
  - sbt ++$TRAVIS_SCALA_VERSION test package
  - git diff --exit-code # check scalariform
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
