version: ~> 1.0
import: scala/scala-dev:travis/default.yml

language: scala
env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11
scala:
  - 3.0.0-M1
  - 2.12.12
  - 2.13.3

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues package
  - git diff --exit-code # check scalariform
