sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.coursier
jdk:
  - oraclejdk8
  - openjdk11
language: scala
script:
  - sbt +test +package
  - git diff --exit-code # check scalariform
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
